In [2]:
#create a 1d array
import numpy as np
arr= np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [12]:
#fill 2d array w zeros
x= np.zeros((2,4))
x

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [8]:
#fill 2d array w ones
x= np.ones((3,6))
x

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [11]:
#create a full func w 2d filler of 7
x= np.full((2,4),7)
x

array([[7, 7, 7, 7],
       [7, 7, 7, 7]])

In [16]:
#implement slicing for following
import numpy as np
arr=np.identity(6)
print(arr)
print(arr[:,:])
print(arr[2:5,0:3])

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]
[[0. 0. 1.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [13]:
#implement to find out the dimensions of given array
import numpy as np
x= np.array([[1,2,3],[4,5,6]])
x.ndim

2

In [15]:
#create a 8d array with the value [2,2,2,2]
import numpy as np
x= np.array([2,2,2,2],ndmin=8)
print(x)

[[[[[[[[2 2 2 2]]]]]]]]
